services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - ./auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  task-db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - ./task-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    volumes:
      - ./user-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: ./auth-service
    environment:
      DATABASE_URL: postgres://admin:secret@auth-db:5432/authdb
      JWT_SECRET: dev-shared-secret
      JWT_EXPIRES_IN: 1h
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - auth-db

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html

  task-service:
    build: ./task-service
    environment:
      DATABASE_URL: postgres://admin:secret@task-db:5432/taskdb
      DB_HOST: task-db
      DB_USER: admin
      DB_PASSWORD: secret
      DB_NAME: taskdb
      JWT_SECRET: dev-shared-secret
      PORT: 3002
      NODE_ENV: development
    ports:
      - "3002:3002"
    depends_on:
      - task-db

  user-service:
    build: ./user-service
    environment:
      DATABASE_URL: postgres://admin:secret@user-db:5432/userdb
      JWT_SECRET: dev-shared-secret
      PORT: 3003
      NODE_ENV: development
    ports:
      - "3003:3003"
    depends_on:
      - user-db